services:
  app:
    image: public.ecr.aws/docker/library/node:20.18.0-bookworm-slim
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 127.0.0.1:3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_DB: ${MY_ENV_VAR} 

  mysql:
    image: public.ecr.aws/docker/library/mysql:8.4
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data: